import "./globals.css";
import Navbar from "./components/Navabar";
import Footer from "./components/Footer";
import Providers from "./provider";
import { AuthProvider } from "./context/AuthProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/remixicon@4.7.0/fonts/remixicon.css"
          rel="stylesheet"
          precedence="default"
        />
      </head>
      <body className={`antialiased`}>
        <Providers>
          <AuthProvider>
            <Navbar />
            {children}
            <Footer />
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
